In [14]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [15]:
#load the trained model
model = load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [16]:
#load the encoder and scaler
with open('onehot_encoder_geo.pkl','rb') as file:
    label_encoder_geo = pickle.load(file)

with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)

with open('Scaler.pkl','rb') as file:
    Scaler = pickle.load(file)

In [34]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [35]:
#one hot encode'geography'
geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns = label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

/Users/namanvats/Desktop/projects of ai/ann project-1/venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [36]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [37]:
#concatination one hot model
input_df = pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [40]:
# Encode Gender
gender_encoded = label_encoder_gender.transform([input_data['Gender']])[0]

print(gender_encoded)

1

In [41]:
# Add Geography
input_df = pd.concat(
    [input_df, geo_encoded_df],axis=1
)

In [42]:
print(input_df)

   CreditScore Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600   Male   40       3    60000              2          1

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1            50000               1.0                0.0

   Geography_Spain  Geography_France  Geography_Germany  Geography_Spain
0              0.0               1.0                0.0              0.0

In [43]:
# Scale
input_scaled = Scaler.transform(input_df)

print(input_scaled)

DuplicateError: Expected unique column names, got:
- 'Geography_France' 2 times
- 'Geography_Germany' 2 times
- 'Geography_Spain' 2 times